### ISSUE TITLE
example-vite failed to build on Windows

### ISSUE THREAD

**Issue by hut36** [powersync-ja/powersync-js#107]
Windows version: Windows 11 23H2 22631.3296
powersync-js: 68738c587f

The same build command (`pnpm -F example-vite build`) works on macOS.

The error output:

```
D:\repos\powersync-js> pnpm -F example-vite build

> example-vite@0.0.10 build D:\repos\powersync-js\demos\example-vite
> vite build

vite v5.1.4 building for production...
✓ 3 modules transformed.
x Build failed in 52ms
error during build:
Error: [commonjs--resolver] Failed to resolve entry for package "@journeyapps/powersync-sdk-web". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///D:/repos/powersync-js/demos/example-vite/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:48038:17)
    at resolvePackageEntry (file:///D:/repos/powersync-js/demos/example-vite/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:48035:5)
    at tryNodeResolve (file:///D:/repos/powersync-js/demos/example-vite/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:47805:20)
    at Object.resolveId (file:///D:/repos/powersync-js/demos/example-vite/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:47568:28)
    at file:///D:/repos/powersync-js/demos/example-vite/node_modules/rollup/dist/es/shared/node-entry.js:18731:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/repos/powersync-js/demos/example-vite/node_modules/rollup/dist/es/shared/node-entry.js:18631:28)
    at async resolveId (file:///D:/repos/powersync-js/demos/example-vite/node_modules/rollup/dist/es/shared/node-entry.js:17298:26)
    at async ModuleLoader.resolveId (file:///D:/repos/powersync-js/demos/example-vite/node_modules/rollup/dist/es/shared/node-entry.js:17712:15)
    at async Object.resolveId (file:///D:/repos/powersync-js/demos/example-vite/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:8171:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/repos/powersync-js/demos/example-vite/node_modules/rollup/dist/es/shared/node-entry.js:18631:28)
```

**Comment by hut36** [comment]
Solved by clean and rebuild.
